---
# Handlers for nftables

- name: "Restart nftables"
  systemd:
    name: "nftables"
    state: restarted

- name: "Restart nft-blacklist.timer"
  systemd:
    name: "nft-blacklist.timer"
    state: restarted
...
