---
# Handlers for nftables

- name: "Restart nftables"
  systemd:
    name: "nftables"
    state: restarted

- name: "Restart nft-geo-filter.timer"
  systemd:
    name: "nft-geo-filter.timer"
    state: restarted
...
